title: CV
description: Welcome on my page!
theme: jekyll-theme-minimal

show_downloads: true

github:
  pdf_url: https://raw.githubusercontent.com/adamkurtyak/adamkurtyak.github.io/refs/heads/main/cv/cv.pdf
